Parameters:
  NotebookInstanceSubNetId:
    Type: AWS::EC2::Subnet::Id
    Description: "Select any subnet id"
    AllowedPattern: ^subnet\-[a-zA-Z0-9]+$
    ConstraintDescription: "You need to inform any subnetid"

  NotebookInstanceSecGroupId:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: "Select the default security group"
    AllowedPattern: ^sg\-[a-zA-Z0-9]+$
    ConstraintDescription: "Select the default security group"

Resources:
  airliquideImageRepo:
      Type: AWS::ECR::Repository
      Properties: 
        RepositoryName: model

  AirliquideBucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: !Sub airliquide-${AWS::Region}-${AWS::AccountId}
        Tags:
          - Key: Name
            Value: !Sub airliquide-${AWS::Region}-${AWS::AccountId}
        AccessControl: Private
        VersioningConfiguration:
          Status: Enabled

  AirliquideRepo:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: Repository for the ML models/images code
      RepositoryName: airliquide

  NotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      NotebookInstanceName: airliquide
      InstanceType: "ml.t2.medium"
      SubnetId: !Ref NotebookInstanceSubNetId
      SecurityGroupIds: !Ref NotebookInstanceSecGroupId
      RoleArn: !GetAtt Airliquide.Arn
      LifecycleConfigName: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
    DependsOn: 
      - NotebookLifecycleConfig
      - Airliquide
      - AirliquideBucket
      - AirliquideRepo

  NotebookLifecycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      NotebookInstanceLifecycleConfigName: !Sub ${AWS::StackName}-lifecycle-config
      OnStart:
        - Content: !Base64 |
            #!/bin/bash
            export HOME=/root/
            export AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            export REGION=$(echo $AVAIL_ZONE | sed 's/[a-z]\+$//')

            echo "Configuring github for AWS credentials"
            git config --global credential.helper '!aws codecommit credential-helper $@'
            git config --global credential.UseHttpPath true
            
            cp /root/.gitconfig /home/ec2-user/ && chown ec2-user:ec2-user /home/ec2-user/.gitconfig

            echo "Create code commit repo"
            git clone https://git-codecommit.${REGION}.amazonaws.com/v1/repos/airliquide /tmp/airliquide-temp

            echo "Master branch"
            cd /tmp/airliquide-temp
            printf "version: 0.2\nphases:\n  build:\n    commands:\n      - echo 'dummy'\n" > buildspec.yml
            git add buildspec.yml
            git commit -a -m ' - repo init'
            git push
            
            echo "model branch"
            git checkout -b model
            git push --set-upstream origin model

            cd ../
            rm -rf /tmp/airliquide-temp

            echo "Downloading model(notebook)"
            git clone https://github.com/yassmhd/AirliquideRepo.git /home/ec2-user/SageMaker/airliquide

            echo "clone branche with base image"
            mkdir -p /home/ec2-user/SageMaker/docker
            git clone --single-branch -b model https://git-codecommit.${REGION}.amazonaws.com/v1/repos/airliquide  /home/ec2-user/SageMaker/docker

            echo "clone and build an image for testing codebuild locally"
            git clone https://github.com/aws/aws-codebuild-docker-images.git /tmp/aws-codebuild
            chmod +x /tmp/aws-codebuild/local_builds/codebuild_build.sh

            docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false

            chown ec2-user:ec2-user -R /home/ec2-user/SageMaker/

            cd /home/ec2-user/SageMaker/airliquide

            parameters="ParameterKey=RepoBranchName,ParameterValue=%s"
            parameters="$parameters ParameterKey=ImageRepoName,ParameterValue=%s"
            parameters="$parameters ParameterKey=ImageTagName,ParameterValue=%s"

            echo "create the model image pipeline"

            aws cloudformation create-stack --stack-name model \
              --template-body file://assets/build-image.yml \
              --parameters $(printf "$parameters" "model" "model" "latest" )


            parameters="$parameters ParameterKey=ModelName,ParameterValue=%s"
            parameters="$parameters ParameterKey=DatasetKeyPath,ParameterValue=%s"
            aws cloudformation create-stack --stack-name model-train-pipeline \
              --template-body file://assets/train-model-pipeline.yml \
              --parameters $(printf "$parameters" "model" "model" "latest" "model" "training_jobs/model" )
            
            echo "Done!"
            
  AirliquideCodeBuild:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: AirliquideCodeBuild
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "Admin"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  Airliquide:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: Airliquide
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "sagemaker.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codepipeline.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "events.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "Admin"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"

Outputs:
  NotebookInstanceId:
    Value: !Ref NotebookInstance
  NotebookInstanceLifecycleConfigId:
    Value: !Ref NotebookLifecycleConfig


